---
- name: Debian > Swap > Disable
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Debian > Swap > Disable in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: "^.*swap.*$"
    replace: ""
    backup: true
