---
- name: Metadata > Facts
  ansible.builtin.setup:
    gather_subset:
      - all

- name: Metadata > Prerequisites > OS
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version == "12"
    success_msg: "This role is supported on Debian 12"
    fail_msg: "This role is only supported on Debian 12"

- name: Metadata > Prerequisites > Architecture
  ansible.builtin.assert:
    that:
      - ansible_architecture == "x86_64"
    success_msg: "This role is supported on amd64 (x86_64) architecture"
    fail_msg: "This role is only supported on amd64 (x86_64) architecture"

- name: Metadata > Directory
  ansible.builtin.file:
    state: directory
    owner: root
    group: root
    mode: "0755"
    path: "{{ metadata_directory }}"
