---
tailscale_socket: "/run/tailscale/tailscaled.sock"

tailscale_download_arch: >-
  {%- if ansible_architecture == 'x86_64' -%}
  amd64
  {%- elif ansible_architecture == 'aarch64' -%}
  arm64
  {%- else -%}
  amd64
  {%- endif -%}
tailscale_download_version: "1.84.0"
tailscale_download_dst: "/var/cache/download"
tailscale_download_src:
  amd64: "https://dl.tailscale.com/stable/tailscale_{{ tailscale_download_version }}_amd64.deb"
  arm64: "https://dl.tailscale.com/stable/tailscale_{{ tailscale_download_version }}_arm64.deb"
tailscale_download_checksum:
  amd64: "sha256:aca5fda4b433b981356468d6c8f32557b3362c06a445812bc80be9ce0d06ba6f"
  arm64: "sha256:62d4bf2f20895d37d0b179d1686197e179c5062dd83dfaa885909809733a59f9"
