---
metadata_topology_region: >-
  {{
    (
      lookup('env', 'METADATA_TOPOLOGY_REGION') or
      lookup('file', '/var/lib/instance-metadata/topology-region', errors='ignore')
    ) | lower
  }}

metadata_topology_zone: >-
  {{
    (
      lookup('env', 'METADATA_TOPOLOGY_ZONE') or
      lookup('file', '/var/lib/instance-metadata/topology-zone', errors='ignore')
    ) | lower
  }}
