---
tailscale_install: true
tailscale_authkey: "{{ lookup('file', '/var/lib/instance-metadata/tailscale-authkey', errors='ignore') | default(omit) }}"
tailscale_login_server: ""
tailscale_login_timeout: 30
tailscale_advertise_exit_node: ""
tailscale_accept_dns: ""
tailscale_accept_routes: ""
