---
- name: APT > Reset configuration
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/apt/apt.conf.d/00CDMountPoint
    - /etc/apt/apt.conf.d/00trustcdrom
    - /etc/apt/mirrors

- name: APT > Reset preferences
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_fileglob:
    - /etc/apt/listchanges.conf.d/*
    - /etc/apt/preferences.d/*
    - /etc/apt/sources.list.d/*

- name: APT > Cache
  block:
    - name: APT > Cache > Use default repositories
      ansible.builtin.copy:
        dest: /etc/apt/sources.list
        content: "{{ lookup('file', 'sources.list') }}"
        mode: "0644"
      register: apt__repos

    - name: APT > Cache > Update  # noqa: no-handler
      when: apt__repos is changed
      ansible.builtin.apt:
        update_cache: true

- name: APT > Cache > Update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false

- name: APT > Upgrade
  ansible.builtin.apt:
    upgrade: safe
    autoremove: true
    autoclean: true
