---
- name: Download Docker Image | check istio pilot
  ansible.builtin.stat:
    path: "{{ kubernetes_path_image }}/istio-pilot-{{ kubernetes_version_istio }}.tar"
  register: istiod_image
  changed_when: false

- name: Download Docker Image | save istio pilot
  when: not istiod_image.stat.exists
  ansible.builtin.shell: >
    skopeo copy --insecure-policy
    docker://{{ kubernetes_download_image_registry }}/istio/pilot:{{ kubernetes_version_istio }}
    docker-archive:{{ kubernetes_path_image }}/istio-pilot-{{ kubernetes_version_istio }}.tar:istio/pilot:{{ kubernetes_version_istio }}
  args:
    creates: "{{ kubernetes_path_image }}/istio-pilot-{{ kubernetes_version_istio }}.tar"

- name: Download Docker Image | check istio proxyv2
  ansible.builtin.stat:
    path: "{{ kubernetes_path_image }}/istio-proxyv2-{{ kubernetes_version_istio }}.tar"
  register: istiod_image
  changed_when: false

- name: Download Docker Image | save istio proxyv2
  when: not istiod_image.stat.exists
  ansible.builtin.shell: >
    skopeo copy --insecure-policy
    docker://{{ kubernetes_download_image_registry }}/istio/proxyv2:{{ kubernetes_version_istio }}
    docker-archive:{{ kubernetes_path_image }}/istio-proxyv2-{{ kubernetes_version_istio }}.tar:istio/proxyv2:{{ kubernetes_version_istio }}
  args:
    creates: "{{ kubernetes_path_image }}/istio-proxyv2-{{ kubernetes_version_istio }}.tar"
