---
- name: SSH > Server > Install openssh-server Package
  ansible.builtin.apt:
    name:
      - openssh-server
    state: present
    update_cache: true
    install_recommends: false

- name: SSH > Server > Ensure ssh Service is Started and Enabled
  ansible.builtin.systemd_service:
    name: ssh
    state: started
    enabled: true
