---
- name: SSH > System > Prepare Prerequisites
  ansible.builtin.include_tasks: 000-prerequisites.yml

- name: SSH > Server > Install OpenSSH
  when: ssh_openssh
  ansible.builtin.include_tasks: 100-install.yml

- name: SSH > Server > Apply Hardening
  when: ssh_hardening
  ansible.builtin.include_tasks: 200-hardening.yml

- name: SSH > Security > Configure Access Control
  when: ssh_users | length > 0 or ssh_groups | length > 0
  ansible.builtin.include_tasks: 300-access-control.yml
