---
- name: Debian > Prerequisites
  block:
    - name: Debian > Prerequisites > OS
      ansible.builtin.assert:
        that:
          - ansible_distribution == "Debian"
          - ansible_distribution_major_version == "12"
        fail_msg: "This role is only supported on Debian 12"

    - name: Debian > Prerequisites > Architecture
      ansible.builtin.assert:
        that:
          - ansible_architecture == "x86_64"
        fail_msg: "This role is only supported on amd64 (x86_64) architecture"

- name: Metadata > Topology
  ansible.builtin.include_tasks:
    file: 010-metadata-topology.yml

- name: Debian > APT | Reset configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/apt.conf.d/00CDMountPoint
    - /etc/apt/apt.conf.d/00trustcdrom
    - /etc/apt/mirrors

- name: Debian > APT | Reset preferences
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /etc/apt/listchanges.conf.d/*
    - /etc/apt/preferences.d/*
    - /etc/apt/sources.list.d/*

- name: Debian > APT | Set minimal packages
  when: debian_minimal
  ansible.builtin.set_fact:
    debian_packages: "{{ debian_packages | difference(debian_packages_minimal) }}"

- name: Debian > APT | Update cache
  block:
    - name: Debian > APT | Use default repositories
      ansible.builtin.copy:
        content: "{{ lookup('file', 'sources.list') }}"
        dest: /etc/apt/sources.list
      register: debian__repos

    - name: Debian > APT | Update
      when: debian__repos is changed
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

- name: Debian > APT | Update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false

- name: Debian > APT | Upgrade
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
