---
ssh_openssh: true

ssh_hardening: true
ssh_hardening_allow_tcp_forwarding: true
ssh_hardening_allow_root_login: false

ssh_users: []
# ssh_users:
#   - name: user1
#     state: allow
#     key: https://github.com/user1.keys
#   - name: user2
#     state: deny
#     key: https://github.com/user2.keys

ssh_groups: []
# ssh_groups:
#   - name: group1
#     state: allow
#   - name: group2
#     state: deny

ssh_mosh: false
ssh_mosh_ports: "60000:61000"
