---
- name: "Node.js > Configuration > Get npm global prefix"
  ansible.builtin.command: npm config get prefix
  register: nodejs__current_global_prefix
  changed_when: false
  when: nodejs_configure_global_path | bool

- name: "Node.js > Configuration > Configure npm global prefix"
  ansible.builtin.command: npm config set prefix {{ nodejs_global_prefix }}
  when:
    - nodejs_configure_global_path | bool
    - nodejs__current_global_prefix.stdout != nodejs_global_prefix
  become: true
  changed_when: true

- name: "Node.js > Configuration > Ensure global prefix directory exists"
  ansible.builtin.file:
    path: "{{ nodejs_global_prefix }}"
    state: directory
    mode: '0755'
  become: true
  when: nodejs_configure_global_path | bool

- name: "Node.js > Configuration > Ensure npm global bin directory exists"
  ansible.builtin.file:
    path: "{{ nodejs_global_prefix }}/bin"
    state: directory
    mode: '0755'
  become: true
  when: nodejs_configure_global_path | bool

- name: "Node.js > Configuration > Verify npm configuration"
  ansible.builtin.command: npm config get prefix
  register: nodejs__final_global_prefix
  changed_when: false
  when: nodejs_configure_global_path | bool

- name: "Node.js > Configuration > Test npm global installation capability"
  ansible.builtin.shell: |
    set -o pipefail
    npm list -g --depth=0 | head -1
  args:
    executable: /bin/bash
  register: nodejs__npm_global_test
  changed_when: false
  when: nodejs_verify_installation | bool
