---
- name: "Node.js > Prerequisites"
  ansible.builtin.include_tasks: 000-prerequisites.yml

- name: "Node.js > Installation"
  ansible.builtin.include_tasks: 100-nodejs-install.yml

- name: "Node.js > Configuration"
  ansible.builtin.include_tasks: 200-nodejs-configure.yml

- name: "Node.js > Metadata"
  ansible.builtin.include_tasks: 999-metadata.yml
