---
- name: SSH | Install server
  ansible.builtin.apt:
    name:
      - openssh-server
    state: present
    update_cache: true
    install_recommends: false

- name: SSH | Start service
  ansible.builtin.systemd_service:
    name: ssh
    state: started
    enabled: true
