---
- name: Tailscale | assert supported distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Debian']
      - ansible_distribution_release in ['bookworm']
    success_msg: "Supported OS detected: {{ ansible_distribution }} {{ ansible_distribution_release }}"
    fail_msg: "Unsupported OS detected: {{ ansible_distribution }} {{ ansible_distribution_release }}"
