---
- name: Tailscale > Package > Create download directory
  ansible.builtin.file:
    path: "{{ tailscale_download_dst }}"
    state: directory
    mode: 0755

- name: Tailscale > Package > Download
  ansible.builtin.get_url:
    dest: "{{ tailscale_download_dst }}/tailscale_{{ tailscale_download_version }}.deb"
    url: "{{ tailscale_download_src[tailscale_download_arch] }}"
    checksum: "{{ tailscale_download_checksum[tailscale_download_arch] }}"
    mode: 0644

- name: Tailscale > Package > Install
  ansible.builtin.apt:
    deb: "{{ tailscale_download_dst }}/tailscale_{{ tailscale_download_version }}.deb"
    state: present
  notify: Tailscale | Restart

- name: Tailscale > Systemd > Enable
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true

- name: Tailscale > Systemd > Start
  when: (tailscale_authkey | trim) | length > 0
  ansible.builtin.systemd:
    name: tailscaled
    state: started
