---
- name: Tailscale > prerequisites
  when: tailscale_install
  ansible.builtin.include_tasks: 000-prerequisite.yml

- name: Tailscale > install
  when: tailscale_install
  ansible.builtin.include_tasks: 100-install.yml

- name: Tailscale > Configure
  ansible.builtin.include_tasks: 200-configuration.yml

- name: Tailscale > Metadata
  ansible.builtin.import_tasks: 300-metadata.yml
