---
- name: Standard Debian 12
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Print Usage
      when: help | default(h) | default(false)
      failed_when: help | default(h) | default(false)
      ansible.builtin.debug:
        msg:
          - "Usage: @adaptivegears/standard-debian [OPTIONS]"
          - "Options:"
          - "  -h, --help          Show this help message and exit"
          - "  -i, --install       Install packages (DEBIAN_INSTALL, default: true)"
          - "  -m, --minimal       Minimal installation (DEBIAN_MINIMAL, default: false)"
          - "  -p, --prune         Prune unused packages (DEBIAN_PRUNE, default: false)"
          - "  --hostname          Set hostname (env: DEBIAN_HOSTNAME)"
          - "  --topology-region   Set topology region (env: DEBIAN_TOPOLOGY_REGION)"
          - "  --topology-zone     Set topology zone (env: DEBIAN_TOPOLOGY_ZONE)"
          - "Examples:"
          - "  $ bootstrap -- @adaptivegears/standard-debian"
          - "  $ bootstrap -- @adaptivegears/standard-debian --prune"

    - name: Set Facts
      ignore_errors: true
      ansible.builtin.set_fact:
        debian_install: "{{ install | default(i) | default(omit) }}"
        debian_minimal: "{{ minimal | default(m) | default(omit) }}"
        debian_prune: "{{ prune | default(p) | default(omit) }}"
        debian_hostname: "{{ hostname | default(omit) }}"
        metadata_topology_region: "{{ topology_region | default(omit) }}"
        metadata_topology_zone: "{{ topology_zone | default(omit) }}"

    - name: Include Role
      ansible.builtin.include_role:
        name: linux/debian
