---
- name: Debian | Ensure the system is running Debian 12
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version == "12"
    fail_msg: "This role is only supported on Debian 12"

- name: Debian | Ensure the architecture is supported
  ansible.builtin.assert:
    that:
      - ansible_architecture == "amd64"
    fail_msg: "This role is only supported on amd64 architecture"

- name: Debian | Update the APT package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Debian | Perform a distribution upgrade via APT
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true

- name: Debian | Use minimal packages
  when: debian_minimal
  ansible.builtin.set_fact:
    debian_packages: "{{ debian_packages | difference(debian_packages_minimal) }}"

- name: Debian | Configure APT repositories
  block:
    - name: Debian | Configure sources.list to default
      ansible.builtin.copy:
        content: "{{ lookup('file', 'sources.list') }}"
        dest: /etc/apt/sources.list
      register: debian__repos

    - name: Debian | Update APT cache
      when: debian__repos is changed
      ansible.builtin.apt:
        update_cache: true
