---
- name: Debian | Gather APT packages
  ansible.builtin.package_facts:
    manager: auto

- name: Debian | Get installed packages
  ansible.builtin.set_fact:
    debian__pkgs: "{{ ansible_facts.packages.keys() | list }}"

- name: Debian | Get packages to install
  ansible.builtin.set_fact:
    debian__pkgs_minimal: "{{ debian_packages | difference(debian_packages_minimal) }}"
    debian__pkgs_present: "{{ debian_packages | difference(debian__pkgs) }}"

- name: Debian | Exclude specific packages from installation
  ansible.builtin.set_fact:
    debian__pkgs_present: "{{ (debian__pkgs_present | difference(debian_packages_noinstall)) | unique | sort }}"

- name: Debian | Display packages to install
  ansible.builtin.debug:
    var: debian__pkgs_present

- name: Debian | Install packages
  ansible.builtin.apt:
    name: "{{ debian__pkgs_present }}"
    state: present
    install_recommends: false
