---
- name: Debian > Pre-configure | Get installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Debian > Pre-configure | Iptables
  when: '"iptables" in ansible_facts.packages'
  community.general.alternatives:
    name: "{{ item.name }}"
    link: "{{ item.link }}"
    path: "{{ item.path }}"
  loop:
    - name: "iptables"
      link: "/usr/sbin/iptables"
      path: "/usr/sbin/iptables-nft"
    - name: "ip6tables"
      link: "/usr/sbin/ip6tables"
      path: "/usr/sbin/ip6tables-nft"

- name: Debian > Pre-configure | Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Debian > Pre-configure | Disable swap in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: "^.*swap.*$"
    replace: ""
    backup: true

- name: Debian > Pre-configure | Configure Kernel
  ansible.builtin.import_tasks: 310-pre-configure-kernel.yml
