---
- name: Debian | Gather APT packages
  ansible.builtin.package_facts:
    manager: auto

- name: Debian | Update alternatives for iptables
  when: "iptables" in ansible_facts.packages
  community.general.alternatives:
    name: "{{ item.name }}"
    link: "{{ item.link }}"
    path: "{{ item.path }}"
  loop:
    - name: "iptables"
      link: "/usr/sbin/iptables"
      path: "/usr/sbin/iptables-nft"
    - name: "ip6tables"
      link: "/usr/sbin/ip6tables"
      path: "/usr/sbin/ip6tables-nft"
