- name: Debian > Kernel | Enable task_delay
  ansible.builtin.sysctl:
    name: kernel.task_delayacct
    value: "1"
    state: present
    reload: true

- name: Debian > Kernel | Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Debian > Kernel | Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true

- name: Debian > Kernel | Enable IPv6 router advertisements
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "2"
    state: present
    reload: true

- name: Debian > Kernel | Hardening kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items:
    - name: vm.panic_on_oom
      value: "0"
    - name: vm.overcommit_memory
      value: "1"
    - name: kernel.panic
      value: "10"
    - name: kernel.panic_on_oops
      value: "1"
