---
- name: Debian | Gather package dependencies
  ansible.builtin.command: apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances {{ debian_packages | join(' ') }}
  register: debian_packages_dependencies
  changed_when: false

- name: Debian | Get unique dependencies
  ansible.builtin.set_fact:
    debian_packages_dependencies: "{{ debian_packages_dependencies.stdout | split('\n') | reject('match', '^(\\s+|<)') | unique | sort }}"

- name: Debian | Display unique dependencies
  ansible.builtin.debug:
    var: debian_packages_dependencies

- name: Debian | Gather APT packages
  ansible.builtin.package_facts:
    manager: auto

- name: Debian | Gather manually installed packages
  ansible.builtin.shell: apt-mark showmanual
  register: debian_packages_manual
  changed_when: false

- name: Debian | Set manually installed packages
  ansible.builtin.set_fact:
    debian_packages_manual: "{{ debian_packages_manual.stdout | split('\n') | sort }}"

- name: Debian | Mark packages as manually installed
  ansible.builtin.shell: |
    {% for package in (debian_packages_dependencies | difference(debian_packages_manual)) %}
    {% if package in ansible_facts.packages %}
    apt-mark manual "{{ package }}"
    {% endif %}
    {% endfor %}
    :
  changed_when: false

- name: Debian | Get packages to remove
  ansible.builtin.set_fact:
    debian_packages_remove: "{{ ansible_facts.packages.keys() | list | difference(debian_packages_dependencies) | unique | sort }}"

- name: Identify packages to autoremove
  ansible.builtin.shell: |
    dpkg --get-selections | grep -w "install" | cut -f1
  register: debian_packages_installed

- name: Debian | Display installed packages
  ansible.builtin.debug:
    var: debian_packages_installed

- name: Debian | Get packages to autoremove
  ansible.builtin.set_fact:
    debian_packages_installed: "{{ debian_packages_installed.stdout | split('\n') | map('trim') | reject('empty') }}"
    debian_packages_remove: "{{ debian_packages_remove | intersect(debian_packages_installed) }}"

- name: Debian | Display packages to remove
  ansible.builtin.debug:
    var: debian_packages_remove


# - name: Debian | Remove packages
#   ansible.builtin.apt:
#     name: "{{ debian_packages_remove }}"
#     state: absent
#     autoremove: true
#     purge: true
