---
- name: Debian | Gather package dependencies
  ansible.builtin.command: apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances {{ debian_packages | join(' ') }}
  register: debian_packages_dependencies

- name: Debian | Get unique dependencies
  ansible.builtin.set_fact:
    debian_packages_dependencies: "{{ debian_packages_dependencies | split('\n') | reject('match', '^(\\s+|<)') | unique | sort }}"

- name: Debian | Display dependencies
  ansible.builtin.debug:
    var: debian_packages_dependencies

- name: Debian | Get unique dependencies
  ansible.builtin.set_fact:
    debian_packages_dependencies: "{{ debian_packages_dependencies.results | map(attribute='stdout') | join('\n') | split('\n') | reject('match', '^(\\s+|<)') | unique | sort }}"

- name: Debian | Display unique dependencies
  ansible.builtin.debug:
    var: debian_packages_dependencies

- name: Debian | Gather APT packages
  ansible.builtin.package_facts:
    manager: auto

- name: Debian | Mark packages as manually installed
  when: item in ansible_facts.packages
  ansible.builtin.command: apt-mark manual "{{ item }}"
  loop: "{{ debian_packages_dependencies }}"
  changed_when: false

- name: Debian | Get packages to remove
  ansible.builtin.set_fact:
    debian_packages_remove: "{{ ansible_facts.packages.keys() | list | difference(debian_packages_dependencies) | sort }}"

- name: Debian | Display packages to remove
  ansible.builtin.debug:
    var: debian_packages_remove

# - name: Debian | Remove packages
#   ansible.builtin.apt:
#     name: "{{ debian_packages_remove }}"
#     state: absent
#     autoremove: true
#     purge: true
