---
- name: Debian | Gather package dependencies (async)
  ansible.builtin.command: >
    apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts
    --no-breaks --no-replaces --no-enhances "{{ async_item }}"
  async: 300
  poll: 0
  loop: "{{ debian_packages | sort }}"
  loop_control:
    loop_var: "async_item"
  register: async_results

- name: Debian | Wait for all dependency gathering jobs to complete
  ansible.builtin.async_status:
    jid: "{{ async_item.ansible_job_id }}"
  loop: "{{ async_results.results }}"
  loop_control:
    loop_var: "async_item"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30
  delay: 5

- name: Debian | Aggregate dependency results
  ansible.builtin.set_fact:
    debian_packages_dependencies: "{{ async_results.results | map(attribute='stdout') | join('\n') | split('\n') | reject('match', '^(\\s+|<)') | unique | sort }}"

- name: Debian | Display dependencies
  ansible.builtin.debug:
    var: debian_packages_dependencies

- name: Debian | Get unique dependencies
  ansible.builtin.set_fact:
    debian_packages_dependencies: "{{ debian_packages_dependencies.results | map(attribute='stdout') | join('\n') | split('\n') | reject('match', '^(\\s+|<)') | unique | sort }}"

- name: Debian | Display unique dependencies
  ansible.builtin.debug:
    var: debian_packages_dependencies

- name: Debian | Gather APT packages
  ansible.builtin.package_facts:
    manager: auto

- name: Debian | Mark packages as manually installed
  when: item in ansible_facts.packages
  ansible.builtin.command: apt-mark manual "{{ item }}"
  loop: "{{ debian_packages_dependencies }}"
  changed_when: false

- name: Debian | Get packages to remove
  ansible.builtin.set_fact:
    debian_packages_remove: "{{ ansible_facts.packages.keys() | list | difference(debian_packages_dependencies) | sort }}"

- name: Debian | Display packages to remove
  ansible.builtin.debug:
    var: debian_packages_remove

# - name: Debian | Remove packages
#   ansible.builtin.apt:
#     name: "{{ debian_packages_remove }}"
#     state: absent
#     autoremove: true
#     purge: true
