---
- name: Debian | Set MOTD
  ansible.builtin.copy:
    content: "{{ lookup('file', 'motd.txt') }}"
    dest: /etc/motd

- name: Debian | Configure locales
  block:
    - name: Debian | Generate {{ debian_locale }} locale
      community.general.locale_gen:
        name: "{{ debian_locale }}"
        state: present

    - name: Debian | Set default locale
      ansible.builtin.copy:
        content: |
          LANG={{ debian_locale }}
        dest: /etc/default/locale

- name: Debian | Configure time
  block:
    - name: Debian | Set timezone
      community.general.timezone:
        name: "{{ debian_timezone }}"

    - name: Debian | Use systemd-timesyncd
      ansible.builtin.systemd_service:
        name: systemd-timesyncd
        state: started
        enabled: true

    - name: Debian | Set timesyncd configuration
      ansible.builtin.copy:
        content: |
          [Time]
          NTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org
        dest: /etc/systemd/timesyncd.conf
      notify: Restart systemd-timesyncd

- name: Debian | Configure DNS using systemd-resolved
  block:
    - name: Debian | Use systemd-resolved
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: started
        enabled: true

    - name: Debian | Set DNS servers
      ansible.builtin.copy:
        content: |
          [Resolve]
          DNS=1.1.1.1 1.0.0.1
          FallbackDNS=8.8.8.8 8.8.4.4
          Cache=yes
          CacheFromLocalhost=no
          CacheMaxAge=60
        dest: /etc/systemd/resolved.conf
      notify: Restart systemd-resolved

- name: Debian | Configure "debian" user
  block:
    - name: Debian | Create "debian" user
      ansible.builtin.user:
        name: "{{ debian_user }}"
        state: present
        groups: "{{ debian_user_groups }}"
        home: "{{ debian_user_home }}"
        shell: "{{ debian_user_shell }}"
        create_home: true
        home: /home/debian

    - name: Debian | Add "debian" user to sudoers
      ansible.builtin.copy:
        dest: /etc/sudoers.d/{{ debian_user }}
        content: "{{ debian_user }} ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: '0440'
