---
- name: Debian | Set MOTD
  ansible.builtin.copy:
    content: "{{ lookup('file', 'motd.txt') }}"
    dest: /etc/motd

- name: Debian | Configure locales
  block:
    - name: Debian | Generate {{ debian_locale }} locale
      community.general.locale_gen:
        name: "{{ debian_locale }}"
        state: present

    - name: Debian | Set default locale
      ansible.builtin.copy:
        content: |
          LANG={{ debian_locale }}
        dest: /etc/default/locale

- name: Debian | Configure time
  block:
    - name: Debian | Set timezone
      community.general.timezone:
        name: "{{ debian_timezone }}"

    - name: Debian | Use systemd-timesyncd
      ansible.builtin.systemd_service:
        name: systemd-timesyncd
        state: started
        enabled: true

    - name: Debian | Set timesyncd configuration
      ansible.builtin.copy:
        content: |
          [Time]
          NTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org
        dest: /etc/systemd/timesyncd.conf
      notify: Restart systemd-timesyncd

- name: Debian | Configure APT repositories
  block:
    - name: Debian | Configure sources.list to default
      ansible.builtin.copy:
        content: "{{ lookup('file', 'sources.list') }}"
        dest: /etc/apt/sources.list
      register: debian__repos

    - name: Debian | Update APT cache
      when: debian__repos is changed
      ansible.builtin.apt:
        update_cache: true
