---
- name: Debian | Set MOTD
  ansible.builtin.copy:
    content: "{{ lookup('file', 'motd.txt') }}"
    dest: /etc/motd

- name: Debian | Configure locales
  block:
    - name: Debian | Generate {{ debian_locale }} locale
      community.general.locale_gen:
        name: "{{ debian_locale }}"
        state: present

    - name: Debian | Set default locale
      ansible.builtin.copy:
        content: |
          LANG={{ debian_locale }}
        dest: /etc/default/locale

- name: Debian | Configure timezone
  community.general.timezone:
    name: "{{ debian_timezone }}"
