---
- name: Debian | Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Debian | Upgrade APT packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true

- name: Debian | Gather APT packages
  ansible.builtin.package_facts:
    manager: auto

- name: Debian | Get installed packages
  ansible.builtin.set_fact:
    debian_packages_installed: "{{ ansible_facts.packages.keys() | list }}"

- name: Debian | Get packages to install
  ansible.builtin.set_fact:
    debian_packages_install: "{{ debian_packages | difference(debian_packages_installed) }}"

- name: Debian | Display packages to install
  ansible.builtin.debug:
    var: debian_packages_install
    verbosity: 1
