---
- name: Debian | Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Debian | Upgrade APT packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true

- name: Debian | Gather APT packages
  ansible.builtin.package_facts:
    manager: auto

- name: Debian | Get installed packages
  ansible.builtin.set_fact:
    debian_packages_installed: "{{ ansible_facts.packages.keys() | list }}"

- name: Debian | Get packages to install
  ansible.builtin.set_fact:
    debian_packages_install: "{{ debian_packages | difference(debian_packages_installed) }}"

- name: Debian | Conditional installation for QEMU packages
  when: ansible_virtualization_type != "qemu"
  vars:
    debian_packages_qemu:
      - qemu-guest-agent
      - qemu-utils
  ansible.builtin.set_fact:
    debian_packages_install: "{{ debian_packages_install | difference(debian_packages_qemu) }}"

- name: Debian | Exclude specific packages from installation
  vars:
    debian_packages_install_exclude:
      - efibootmgr
      - grub-cloud-amd64
      - grub-pc
      - grub-efi-amd64
      - grub-efi-amd64-signed
      - shim-signed
      - cloud-init
      - cloud-utils
      - cloud-initramfs-growroot
      - intel-microcode
      - amd64-microcode
  ansible.builtin.set_fact:
    debian_packages_install: "{{ debian_packages_install | difference(debian_packages_install_exclude) }}"

- name: Debian | Display packages to install
  ansible.builtin.debug:
    var: debian_packages_install

- name: Debian | Install packages
  ansible.builtin.apt:
    name: "{{ debian_packages_install }}"
    state: present
    install_recommends: false

- name: Debian | Update alternatives for iptables
  community.general.alternatives:
    name: "{{ item.name }}"
    link: "{{ item.link }}"
    path: "{{ item.path }}"
  loop:
    - name: "iptables"
      link: "/usr/sbin/iptables"
      path: "/usr/sbin/iptables-nft"
    - name: "ip6tables"
      link: "/usr/sbin/ip6tables"
      path: "/usr/sbin/ip6tables-nft"

- name: Debian | Gather package dependencies
  ansible.builtin.command: apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances "{{ item }}"
  loop: "{{ debian_packages | sort }}"
  register: debian_packages_dependencies
  changed_when: false

- name: Debian | Display dependencies
  ansible.builtin.debug:
    var: debian_packages_dependencies

- name: Debian | Get unique dependencies
  ansible.builtin.set_fact:
    debian_packages_dependencies: "{{ debian_packages_dependencies.results | map(attribute='stdout') | join('\n') | split('\n') | reject('match', '^(\\s+|<)') | unique | sort }}"

- name: Debian | Display unique dependencies
  ansible.builtin.debug:
    var: debian_packages_dependencies

- name: Debian | Gather APT packages
  ansible.builtin.package_facts:
    manager: auto

- name: Debian | Mark packages as manually installed
  when: item in ansible_facts.packages
  ansible.builtin.command: apt-mark manual "{{ item }}"
  loop: "{{ debian_packages_dependencies }}"
  changed_when: false

- name: Debian | Get packages to remove
  ansible.builtin.set_fact:
    debian_packages_remove: "{{ ansible_facts.packages.keys() | list | difference(debian_packages_dependencies) | sort }}"

- name: Debian | Display packages to remove
  ansible.builtin.debug:
    var: debian_packages_remove
