---
- name: Debian | Prerequisite
  ansible.builtin.import_tasks: 100-prerequisite.yaml

- name: Debian | Auto Install
  ansible.builtin.import_tasks: 200-auto-install.yaml

- name: Debian | Pre-configuration
  ansible.builtin.import_tasks: 300-pre-configure.yaml

- name: Debian | Auto Uninstall
  ansible.builtin.import_tasks: 400-auto-uninstall.yaml

- name: Debian | Post-configuration
  ansible.builtin.import_tasks: 500-post-configuration.yaml
