---
- name: Debian | Prerequisite
  ansible.builtin.import_tasks: 100-prerequisite.yaml

- name: Debian | Auto Install
  ansible.builtin.import_tasks: 200-auto-install.yaml

- name: Debian | Configure
  ansible.builtin.import_tasks: 300-configure.yaml

- name: Debian | Auto Remove
  ansible.builtin.import_tasks: 400-auto-remove.yaml
