---
- name: Debian | Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Debian | Upgrade APT packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true

- name: Debian | Gather APT packages
  ansible.builtin.package_facts:
    manager: auto

- name: Debian | Get installed packages
  ansible.builtin.set_fact:
    debian_packages_installed: "{{ ansible_facts.packages.keys() | list }}"

- name: Debian | Get packages to install
  ansible.builtin.set_fact:
    debian_packages_install: "{{ debian_packages | difference(debian_packages_installed) }}"

- name: Debian | Display packages to install
  ansible.builtin.debug:
    var: debian_packages_install

- name: Debian | Conditional installation for Intel Microcode
  when: ansible_processor[1] == "GenuineIntel" and 'intel-microcode' in debian_packages_install
  ansible.builtin.set_fact:
    debian_packages_install: "{{ debian_packages_install | difference(['intel-microcode']) }}"

- name: Debian | Conditional installation for AMD Microcode
  when: ansible_processor[1] == "AuthenticAMD" and 'amd64-microcode' in debian_packages_install
  ansible.builtin.set_fact:
    debian_packages_install: "{{ debian_packages_install | difference(['amd64-microcode']) }}"

- name: Debian | Conditional installation for QEMU packages
  when: ansible_virtualization_type != "qemu"
  vars:
    debian_packages_qemu:
      - qemu-guest-agent
      - qemu-utils
  ansible.builtin.set_fact:
    debian_packages_install: "{{ debian_packages_install | difference(debian_packages_qemu) }}"

- name: Debian | Exclude specific packages from installation
  vars:
    debian_packages_install_exclude:
      - efibootmgr
      - grub-cloud-amd64
      - grub-pc
      - grub-efi-amd64
      - grub-efi-amd64-signed
      - shim-signed
      - cloud-init
      - cloud-utils
      - cloud-initramfs-growroot
  ansible.builtin.set_fact:
    debian_packages_install: "{{ debian_packages_install | difference(debian_packages_install_exclude) }}"

- name: Debian | Display packages to install
  ansible.builtin.debug:
    var: debian_packages_install
