---
- name: Kubernetes > Prerequisites > Containerd
  ansible.builtin.include_tasks:
    file: 010-containerd.yml

- name: Kubernetes > Prerequisites > Kubeadm
  ansible.builtin.include_tasks:
    file: 020-kubeadm.yml
