---
- name: Kubernetes > Prerequisites > Apt > Update Cache
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true

- name: Kubernetes > Prerequisites > Apt > Repository Dependencies
  ansible.builtin.apt:
    state: present
    install_recommends: false
    name:
      - apt-transport-https
      - curl
      - gnupg
      - lsb-release

- name: Kubernetes > Prerequisites > Containerd
  ansible.builtin.include_tasks:
    file: 010-containerd.yml

- name: Kubernetes > Prerequisites > Kubeadm
  ansible.builtin.include_tasks:
    file: 020-kubeadm.yml
