---
- name: Kubernetes > Prerequisites > Containerd
  ansible.builtin.apt:
    name:
      - containerd
      - containernetworking-plugins
    state: present
    install_recommends: true

- name: Kubernetes > Prerequisites > Containerd > Configure
  register: kubernetes__containerd_config
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0644"
    content: |
      version = 2
      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
          sandbox_image = "registry.k8s.io/pause:3.10"
          [plugins."io.containerd.grpc.v1.cri".cni]
            bin_dir = "/usr/lib/cni"
            conf_dir = "/etc/cni/net.d"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            runtime_type = "io.containerd.runc.v2"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true
        [plugins."io.containerd.internal.v1.opt"]
          path = "/var/lib/containerd/opt"

- name: Kubernetes > Prerequisites > Containerd > Restart
  when: kubernetes__containerd_config.changed
  ansible.builtin.systemd:
    name: containerd
    state: restarted
