---
- name: Kubernetes > Prerequisites > Kubeadm > Apt
  ansible.builtin.apt:
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    name:
      - apt-transport-https
      - curl
      - gnupg
      - lsb-release

- name: Kubernetes > Prerequisites > Kubeadm > Create Keyrings Directory
  ansible.builtin.file:
    state: directory
    mode: "0755"
    owner: root
    group: root
    path: /etc/apt/keyrings
