---
- name: Kubernetes > Prequisites > Kernel > Modules
  community.general.modprobe:
    state: present
    persistent: present
    name: "{{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: Kubernetes > Prequisites > Kernel > Sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items:
    - name: "net.bridge.bridge-nf-call-iptables"
      value: "1"
    - name: "net.bridge.bridge-nf-call-ip6tables"
      value: "1"
    - name: "net.ipv4.ip_forward"
      value: "1"
