---
- name: Kubernetes > System | Get public IP
  ansible.builtin.set_fact:
    kubernetes__public_ip: "{{ lookup('ansible.builtin.file', '/var/lib/instance-metadata/ipv4-public-ingress') }}"

- name: Kubernetes > System | Set public IP
  when: kubernetes_public_ip | length == 0 and kubernetes__public_ip | length > 0
  ansible.builtin.set_fact:
    kubernetes_public_ip: "{{ kubernetes__public_ip }}"

