---
### Kubernetes | Assertions ###################################################
- name: Kubernetes | assert configuration
  ansible.builtin.assert:
    that:
      - "kubernetes_role in ['server', 'agent']"

### Kubernetes | State ########################################################
- name: Kubernetes | create directory for state
  ansible.builtin.file:
    path: "{{ kubernetes_path_statedir }}"
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Kubernetes | configure addons
  when: kubernetes_role == 'server'
  ansible.builtin.import_tasks: 051-setup-addons.yml

### Kubernetes | Configuration ################################################
- name: Kubernetes | create directory for configuration
  ansible.builtin.file:
    path: "{{ kubernetes_path_confdir }}/"
    state: directory
    mode: "0755"

- name: Kubernetes | create configuration for registries
  ansible.builtin.template:
    src: registries.yml.j2
    dest: "{{ kubernetes_path_confdir }}/registries.yaml"
    owner: root
    group: root
    mode: 0644

- name: Kubernetes | create configuration
  ansible.builtin.import_tasks: 052-setup-config.yml

- name: Systemd | service state
  ansible.builtin.import_tasks: 053-setup-systemd.yml

- name: Kubernetes | wait for readiness
  ansible.builtin.wait_for:
    path: "{{ kubernetes_path_statedir }}/{{ kubernetes_role }}"
