---
- name: Kubernetes > Addon | Create manifests directory
  ansible.builtin.file:
    path: "{{ kubernetes_path_statedir }}/server/manifests"
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Kubernetes > Addon | Enable Gateway API
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v{{ kubernetes_version_gatewayapi }}/experimental-install.yaml"
    dest: "{{ kubernetes_path_statedir }}/server/manifests/gatewayapi.yaml"
    owner: root
    group: root
    mode: 0644

- name: Kubernetes > Addon | Disable local-storage
  ansible.builtin.file:
    path: "{{ kubernetes_path_statedir }}/server/manifests/local-storage.yaml.skip"
    state: touch
    owner: root
    group: root
    mode: 0644
    modification_time: preserve
    access_time: preserve
