---
- name: Kubernetes | set api server
  when: kubernetes__present and kubernetes_apiserver == '127.0.0.1'
  ansible.builtin.set_fact:
    kubernetes_apiserver: "{{ ansible_default_ipv4.address }}"

- name: Kubernetes | create configuration
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ kubernetes_path_confdir }}/config.yaml"
    owner: root
    group: root
    mode: 0644
  register: kubernetes__config

- name: Kubernetes | create directory for configuration
  ansible.builtin.file:
    path: "{{ kubernetes_path_confdir }}/config.yaml.d"
    state: directory
    mode: "0755"

- name: Kubernetes | set configuration for server network
  when: kubernetes_role == 'server'
  ansible.builtin.template:
    src: config.yaml.d/000-network.yaml.j2
    dest: "{{ kubernetes_path_confdir }}/config.yaml.d/000-network.yaml"
    owner: root
    group: root

- name: Kubernetes | get configuration for token
  ansible.builtin.stat:
    path: "{{ kubernetes_path_confdir }}/config.yaml.d/010-token.yaml"
  register: kubernetes__token

- name: Kubernetes | assert configuration for token
  when: not kubernetes__token.stat.exists
  ansible.builtin.assert:
    that:
      - kubernetes_token is defined
      - kubernetes_token is string
      - kubernetes_token | length > 0
    fail_msg: "Kubernetes | configuration for token is not valid"
    success_msg: "Kubernetes | configuration for token is valid"

- name: Kubernetes | set configuration for token
  when: not kubernetes__token.stat.exists
  ansible.builtin.template:
    src: config.yaml.d/010-token.yaml.j2
    dest: "{{ kubernetes_path_confdir }}/config.yaml.d/010-token.yaml"
    owner: root
    group: root
    mode: 0644

- name: Kubernetes | set configuration for embedded registry
  when: kubernetes_role == 'server'
  ansible.builtin.template:
    src: config.yaml.d/020-embedded-registry.yaml.j2
    dest: "{{ kubernetes_path_confdir }}/config.yaml.d/020-embedded-registry.yaml"
    owner: root
    group: root
    mode: 0644

- name: Kubernetes | get configuration for node labels (when string)
  when: (kubernetes_labels | type_debug) == 'string'
  ansible.builtin.set_fact:
    kubernetes__labels: "{{ kubernetes_labels | split(',') }}"

- name: Kubernetes | get configuration for node labels (when list)
  when: (kubernetes_labels | type_debug) == 'list'
  ansible.builtin.set_fact:
    kubernetes__labels: "{{ kubernetes_labels }}"

- name: Kubernetes | set configuration for node labels
  when: kubernetes__labels is defined and kubernetes__labels | length > 0
  ansible.builtin.template:
    src: config.yaml.d/030-labels.yaml.j2
    dest: "{{ kubernetes_path_confdir }}/config.yaml.d/030-labels.yaml"
    owner: root
    group: root
    mode: 0644

- name: Kubernetes | set configuration for servicelb
  when: kubernetes_public_ip
  ansible.builtin.template:
    src: config.yaml.d/031-labels-enablelb.yaml.j2
    dest: "{{ kubernetes_path_confdir }}/config.yaml.d/031-labels-enablelb.yaml.j2"
    owner: root
    group: root
    mode: 0644

- name: Kubernetes | set configuration for tailscale
  when: kubernetes_tailscale_authkey
  ansible.builtin.template:
    src: config.yaml.d/040-vpn-auth.yaml.j2
    dest: "{{ kubernetes_path_confdir }}/config.yaml.d/040-vpn-auth.yaml"
    owner: root
    group: root
    mode: 0644
  notify:
    - Kubernetes | restart k3s
