---
- name: Systemd | create environment file
  ansible.builtin.template:
    src: k3s.service.env.j2
    dest: /etc/systemd/system/k3s.service.env
    owner: root
    group: root
    mode: 0644
  register: kubernetes__env

- name: Systemd | create service
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644
  register: kubernetes__service

- name: Systemd | get service state
  ansible.builtin.set_fact:
    kubernetes_state: "{{ 'restarted' if kubernetes__config.changed or kubernetes__service.changed or kubernetes__env.changed or kubernetes__binary.changed else 'started' }}"

- name: Systemd | set service state
  ansible.builtin.systemd:
    daemon_reload: "{{ kubernetes__service.changed or kubernetes__env.changed }}"
    name: k3s
    state: "{{ kubernetes_state }}"
    enabled: true
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
