---
- name: Istio | add helm repository
  kubernetes.core.helm_repository:
    name: istio
    repo_url: https://istio-release.storage.googleapis.com/charts

- name: Istio | create namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubernetes_path_confdir }}/k3s.yaml"
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: present
  with_items:
    - istio-system
    - istio-ingress

- name: Istio | setup custom resource definitions
  kubernetes.core.helm:
    kubeconfig: "{{ kubernetes_path_confdir }}/k3s.yaml"
    name: istio-base
    chart_ref: istio/base
    chart_version: "{{ kubernetes_version_istio }}"
    release_namespace: istio-system
    wait: true

- name: Istio | setup istiod
  kubernetes.core.helm:
    kubeconfig: "{{ kubernetes_path_confdir }}/k3s.yaml"
    name: istio
    chart_ref: istio/istiod
    chart_version: "{{ kubernetes_version_istio }}"
    release_namespace: istio-system
    wait: true
    values:
      global:
        proxy:
          privileged: true
      pilot:
        env:
          PILOT_ENABLE_ALPHA_GATEWAY_API: true
