---
- name: Kubernetes > Kubeadm > Pull Kubernetes Images
  ansible.builtin.shell:
    cmd: |
      kubeadm config images pull
  changed_when: false

- name: Kubernetes > Kubeadm > Configure
  ansible.builtin.copy:
    dest: /etc/kubernetes/kubeadm-config.yaml
    owner: root
    group: root
    mode: "0644"
    content: |
      ---
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: InitConfiguration

      localAPIEndpoint:
        advertiseAddress: "{{ lookup('file', '/var/lib/instance-metadata/ipv4-public') | trim }}"
        bindPort: 6443

      nodeRegistration:
        name: "{{ lookup('file', '/var/lib/instance-metadata/hostname') | trim }}"
        criSocket: unix:///var/run/containerd/containerd.sock
        kubeletExtraArgs:
          - name: "node-ip"
            value: "{{ lookup('file', '/var/lib/instance-metadata/ipv4-private') | trim }}"
          - name: "node-labels"
            value: "topology.kubernetes.io/region={{ kubernetes_topology_region }},topology.kubernetes.io/zone={{ kubernetes_topology_zone }}"

      skipPhases:
        - addon/kube-proxy

      ---
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: ClusterConfiguration
      clusterName: "{{ kubernetes_name }}"
      kubernetesVersion: "{{ kubernetes_version_full }}"

      controlPlaneEndpoint: "{{ lookup('file', '/var/lib/instance-metadata/ipv4-public') | trim }}:6443"
      networking:
        dnsDomain: cluster.local
        podSubnet: "{{ kubernetes_subnet_pod }}"
        serviceSubnet: "{{ kubernetes_subnet_service }}"

      ---
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration

      cgroupDriver: systemd

- name: Kubernetes > Kubeadm > Initialize
  ansible.builtin.shell:
    cmd: >-
      kubeadm init
      --config /etc/kubernetes/kubeadm-config.yaml
  changed_when: false
