---
- name: Kubernetes > Kubeadm > Pull Kubernetes Images
  ansible.builtin.shell:
    cmd: |
      kubeadm config images pull
  changed_when: false

- name: Kubernetes > Kubeadm > Configure
  ansible.builtin.copy:
    dest: /etc/kubernetes/kubeadm-config.yaml
    owner: root
    group: root
    mode: "0644"
    content: |
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: InitConfiguration

      localAPIEndpoint:
        advertiseAddress: "{{ ansible_default_ipv4.address }}"
        bindPort: 6443
      nodeRegistration:
        criSocket: unix:///var/run/containerd/containerd.sock
      ---
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: ClusterConfiguration
      clusterName: kubernetes
      kubernetesVersion: "{{ kubernetes_version_full }}"

      controlPlaneEndpoint: "{{ ansible_default_ipv4.address }}:6443"
      networking:
        dnsDomain: cluster.local
        serviceSubnet: "10.96.0.0/12"
        podSubnet: "10.100.0.1/24"
      ---
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration

      cgroupDriver: systemd

- name: Kubernetes > Kubeadm > Initialize
  ansible.builtin.shell:
    cmd: |
      kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  changed_when: false

- name: Kubernetes > Kubeadm > Wait for Kubernetes API
  ansible.builtin.wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 6443
    delay: 5
    timeout: 300
