---
- name: Kubernetes > Kubelet > Enable
  ansible.builtin.systemd_service:
    name: kubelet
    enabled: true

- name: Kubernetes > Kubelet > Start
  ansible.builtin.systemd_service:
    name: kubelet
    state: started
