---
- name: Kubernete > Cilium > Add Helm Repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Kubernete > Cilium > Install
  kubernetes.core.helm:
    kubeconfig: /etc/kubernetes/admin.conf
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "1.16.4"
    release_namespace: kube-system
    wait: true
    values:
      k8sServiceHost: "{{ ansible_default_ipv4.address }}"
      k8sServicePort: 6443
      kubeProxyReplacement: true

      image:
        useDigest: false
      operator:
        image:
          useDigest: false
        replicas: 1
        rollOutPods: true
      rollOutCiliumPods: true
