---
- name: Kubernete > Cilium > Add Helm Repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Kubernete > Cilium > Install
  kubernetes.core.helm:
    kubeconfig: /etc/kubernetes/admin.conf
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "1.16.4"
    release_namespace: kube-system
    wait: true
    values:
      k8sServiceHost: "{{ ansible_default_ipv4.address }}"
      k8sServicePort: 6443

      kubeProxyReplacement: true
      routingMode: native
      ipv4NativeRoutingCIDR: "{{ kubernetes_pod_subnet }}"

      image:
        useDigest: false
      operator:
        image:
          useDigest: false
        replicas: 1
        rollOutPods: true
      rollOutCiliumPods: true

- name: Kubernetes > Cilium > Wait for Readiness
  ansible.builtin.shell: >-
    KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl -n kube-system
    wait --for=condition=ready pod -l app.kubernetes.io/part-of=cilium --timeout=300s
  changed_when: false
