---
- name: Kubernetes > Gateway API > Download
  ansible.builtin.get_url:
    dest: "/tmp/{{ manifest.file }}"
    owner: root
    group: root
    mode: "0644"
    url: "{{ manifest.url }}"

- name: Kubernetes > Gateway API > Install
  ansible.builtin.shell: >-
    KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl apply -f /tmp/{{ manifest.file }}
  changed_when: false
