---
- name: Kubernetes > Cilium > Add Helm Repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Kubernetes > Cilium > Install
  kubernetes.core.helm:
    kubeconfig: /etc/kubernetes/admin.conf
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "1.16.4"
    release_namespace: kube-system
    wait: true
    values:
      image:
        useDigest: false
      operator:
        image:
          useDigest: false
        replicas: 1
        rollOutPods: true
      rollOutCiliumPods: true

      k8sServiceHost: "{{ lookup('ansible.builtin.file', '/var/lib/instance-metadata/ipv4-public') | trim }}"
      k8sServicePort: 6443

      kubeProxyReplacement: true
      routingMode: native
      ipv4NativeRoutingCIDR: "{{ kubernetes_pod_subnet }}"
      ipam:
        mode: kubernetes
      socketLB:
        hostNamespaceOnly: true

      # https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/
      nodePort:
        enabled: true
      l7Proxy: true
      gatewayAPI:
        enabled: true
        hostNetwork:
          enabled: true
      envoy:
        securityContext:
          capabilities:
            keepCapNetBindService: true
            envoy:
              - NET_ADMIN
              - SYS_ADMIN
              - NET_BIND_SERVICE

      hubble:
        enabled: true

- name: Kubernetes > Cilium > Wait for Readiness
  ansible.builtin.shell: >-
    KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl -n kube-system
    wait --for=condition=ready pod -l app.kubernetes.io/part-of=cilium --timeout=300s
  changed_when: false
