---
- name: Kubernetes > Metadata | Save Tailscale Auth Key
  ansible.builtin.copy:
    content: "{{ kubernetes_tailscale_authkey }}"
    dest: /var/lib/instance-metadata/tailscale-authkey
    mode: '0400'
    owner: root
    group: root

- name: Kubernetes > Metadata | Get IPv4 for local traffic
  ansible.builtin.shell: |
    tailscale ip -4
  changed_when: false
  register: tailscale__ipv4

- name: Kubernetes > Metadata | Save IPv4 for local traffic
  ansible.builtin.copy:
    content: "{{ tailscale__ipv4.stdout | trim }}"
    dest: /var/lib/instance-metadata/ipv4-private
    mode: '0644'
    owner: root
    group: root
