---
- name: Kubernetes > Metadata | Tailscale
  when: kubernetes_tailscale_authkey | length > 0
  block:
    - name: Kubernetes > Metadata | Save Tailscale Auth Key
      when: kubernetes_tailscale_authkey | length > 0
      ansible.builtin.copy:
        content: "{{ kubernetes_tailscale_authkey | trim }}"
        dest: /var/lib/instance-metadata/tailscale-authkey
        mode: "0400"
        owner: root
        group: root

    - name: Kubernetes > Metadata | Get IPv4 for local traffic
      ansible.builtin.shell: |
        tailscale ip -4
      changed_when: false
      register: tailscale__ipv4

    - name: Kubernetes > Metadata | Save IPv4 for local traffic
      when: (tailscale__ipv4.stdout | trim) | length > 0
      ansible.builtin.copy:
        content: "{{ tailscale__ipv4.stdout | trim }}"
        dest: /var/lib/instance-metadata/ipv4-private
        mode: "0644"
        owner: root
        group: root

- name: Kubernetes > Metadata | Save Istio Status
  ansible.builtin.copy:
    content: "{{ kubernetes_enable_istio | bool | ternary('true', 'false') }}"
    dest: /var/lib/instance-metadata/kubernetes-enable-istio
    mode: "0444"
    owner: root
    group: root

- name: Kubernetes > Metadata | Save API Server
  when: (kubernetes_apiserver | trim) | length > 0
  ansible.builtin.copy:
    content: "{{ kubernetes_apiserver | trim }}"
    dest: /var/lib/instance-metadata/kubernetes-apiserver
    mode: "0444"
    owner: root
    group: root

- name: Kubernetes > Metadata | Save Datastore
  when: (kubernetes_datastore | trim) | length > 0
  ansible.builtin.copy:
    content: "{{ kubernetes_datastore | trim }}"
    dest: /var/lib/instance-metadata/kubernetes-datastore
    mode: "0444"
    owner: root
    group: root
