---
- name: Kubernetes > Metadata | Get IPv4 for local traffic
  ansible.builtin.shell: >
    tailscale
    --socket {{ tailscale_socket }}
    ip -4
  register: tailscale__ipv4

- name: Kubernetes > Metadata | Save IPv4 for local traffic
  ansible.builtin.copy:
    content: "{{ tailscale__ipv4 }}"
    dest: /var/lib/instance-metadata/ipv4-private
    mode: '0644'
    owner: root
    group: root
