---
- name: Kubernetes > Prerequisites
  ansible.builtin.include_tasks:
    file: 000-prerequisites.yml

- name: Kubernetes > Kubelet > Get Status
  register: kubernetes__kubelet_conf
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf

- name: Kubernetes > Kubeadm
  when: not kubernetes__kubelet_conf.stat.exists
  ansible.builtin.include_tasks:
    file: 100-kubeadm.yml

- name: Kubernetes > Kubelet > Wait for Readiness
  ansible.builtin.wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 6443
    delay: 5
    timeout: 300

- name: Kubernetes > Kubelet
  ansible.builtin.include_tasks:
    file: 110-kubelet.yml

- name: Kubernetes > Kubectl
  ansible.builtin.include_tasks:
    file: 120-kubectl.yml

- name: Kubernetes > Gateway API
  ansible.builtin.include_tasks:
    file: 200-gateway-api.yml
  loop_control:
    loop_var: manifest
  loop:
    - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
      file: gatewayclasses.yaml
      name: GatewayClass
    - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
      file: gateways.yaml
      name: Gateway
    - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
      file: httproutes.yaml
      name: HTTPRoute
    - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
      file: referencegrants.yaml
      name: ReferenceGrant
    - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
      file: grpcroutes.yaml
      name: GRPCRoute
    - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
      file: tlsroutes.yaml
      name: TLSRoute

- name: Kubernetes > Cilium
  ansible.builtin.include_tasks:
    file: 210-cilium.yml
