---
- name: Kubernetes > Prerequisites
  ansible.builtin.include_tasks:
    file: 000-prerequisites.yml

- name: Kubernetes > Kubeadm
  ansible.builtin.include_tasks:
    file: 100-kubeadm.yml

- name: Kubernetes > Kubelet
  ansible.builtin.include_tasks:
    file: 110-kubelet.yml
