---
- name: Download Binaries
  when: kubernetes_install
  ansible.builtin.import_tasks: 010-download.yml

- name: Install Binaries
  when: kubernetes_install
  ansible.builtin.import_tasks: 020-install.yml

- name: Kubernetes | get state
  ansible.builtin.stat:
    path: "{{ kubernetes_path_statedir }}/server/node-token"
  register: kubernetes__present

- name: Kubernetes | set state
  ansible.builtin.set_fact:
    kubernetes__present: "{{ kubernetes__present.stat.exists }}"

- name: Download Docker Images
  when: kubernetes_install and kubernetes_role == 'server' and not kubernetes__present
  ansible.builtin.import_tasks: 030-download-images.yml

- name: Kubernetes | install
  when: kubernetes_install
  block:
    - name: Kubernetes > System | Update
      ansible.builtin.import_tasks: 040-system.yml

    - name: Kubernetes | setup
      when: not kubernetes__present
      block:
        - name: Kubernetes | assert role configuration
          when: kubernetes_role == 'agent'
          ansible.builtin.assert:
            that:
              - kubernetes_apiserver != '127.0.0.1'
            msg: "Agent role requires an API server to join"

        - name: Kubernetes | setup
          ansible.builtin.import_tasks: 050-setup.yml

        - name: Kubernetes | wait for readiness
          ansible.builtin.wait_for:
            host: "{{ kubernetes_apiserver }}"
            port: 6443
            timeout: 90
            state: started

        - name: Kubernetes | set state to present
          ansible.builtin.set_fact:
            kubernetes__present: true

    - name: Kubernetes | configure
      when: kubernetes__present
      block:
        - name: Kubernetes | configuration
          ansible.builtin.import_tasks: 052-setup-config.yml

        - name: Systemd | service state
          ansible.builtin.import_tasks: 053-setup-systemd.yml

- name: Kubernetes | Metadata
  ansible.builtin.import_tasks: 700-metadata.yml
