---
- name: Kubernetes > Prerequisites
  ansible.builtin.include_tasks:
    file: 000-prerequisites.yml

- name: Kubernetes > Kubelet > Get Status
  register: kubernetes__kubelet_conf
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf

- name: Kubernetes > Kubeadm
  when: not kubernetes__kubelet_conf.stat.exists
  ansible.builtin.include_tasks:
    file: 100-kubeadm.yml

- name: Kubernetes > Kubelet
  ansible.builtin.include_tasks:
    file: 110-kubelet.yml

- name: Kubernetes > Kubectl
  ansible.builtin.include_tasks:
    file: 120-kubectl.yml
