---
debian_locale: en_US.UTF-8
debian_timezone: UTC

debian_user: admin
debian_user_groups:
  - adm
  - sudo
debian_user_home: "/home/{{ debian_user }}"
debian_user_shell: /bin/bash

debian_packages_amd64:
  # bootloader
  - efibootmgr
  - grub-cloud-amd64
  - grub-pc
  - grub-efi-amd64
  - grub-efi-amd64-signed
  - shim-signed

  # kernel
  - linux-image-amd64
  - kmod

  # hardware
  - firmware-linux-free
  - intel-microcode
  - amd64-microcode

debian_packages_arm64:
  # bootloader
  - efibootmgr
  - grub-efi-arm64
  - grub-efi-arm64-signed
  - shim-signed

  # kernel
  - linux-image-arm64
  - kmod

  # hardware
  - firmware-linux-free

debian_packages_common:
  # hardware
  - discover
  - dmidecode
  - pciutils
  - udev

  # system
  - base-files
  - libc-bin
  - util-linux
  - util-linux-extra
  - cron
  - logrotate
  - dbus
  - dbus-user-session
  - systemd
  - systemd-resolved
  - systemd-sysv
  - systemd-timesyncd
  - init
  - init-system-helpers
  - sysvinit-utils
  - libnss-systemd
  - libpam-systemd
  - lsb-release
  - unattended-upgrades

  # packages
  - apt
  - apt-listchanges
  - apt-transport-https
  - apt-utils
  - debian-archive-keyring
  - dpkg

  # users
  - base-passwd
  - login
  - passwd
  - sudo

  # filesystem
  - mount
  - fdisk
  - lvm2
  - e2fsprogs

  # shells
  - bash
  - bash-completion
  - dash
  - busybox
  - bsdutils
  - bsdextrautils
  - coreutils
  - diffutils
  - findutils
  - debianutils
  - procps
  - psmisc
  - lsof
  - file
  - tree
  - htop
  - tmux
  - readline-common
  - ncurses-bin
  - ncurses-term
  - whiptail

  # editors
  - mawk
  - nano
  - vim-tiny
  - less
  - grep
  - sed

  # compression
  - cpio
  - tar
  - gzip
  - bzip2
  - xz-utils
  - zstd

  # network
  - netbase
  - hostname
  - ifupdown
  - isc-dhcp-client
  - isc-dhcp-common
  - nftables
  - iptables
  - openssh-server
  - openssh-client
  - traceroute
  - iputils-ping
  - inetutils-telnet
  - bind9-dnsutils
  - socat
  - tcpdump
  - stun-client
  - exip
  - ca-certificates
  - wget
  - curl
  - media-types

  # cloud
  - cloud-init
  - cloud-utils

  # perl
  - perl-base
  - perl

  # python
  - python3
  - python3-requests

  # locale
  - tzdata
  - locales
  - locales-all
  - debconf-i18n

  # cryptography
  - gnupg2
  - gpgv

  # misc
  - distro-info-data
  - publicsuffix
  - iso-codes

# Architecture-specific package selection
debian_packages: >-
  {{
    (debian_packages_common +
     (debian_packages_amd64 if ansible_architecture == 'x86_64' else debian_packages_arm64))
    | unique
  }}

debian_packages_noinstall_amd64:
  # hardware
  - intel-microcode
  - amd64-microcode

  # bootloader
  - efibootmgr
  - grub-cloud-amd64
  - grub-pc
  - grub-efi-amd64
  - grub-efi-amd64-signed
  - shim-signed

debian_packages_noinstall_arm64:
  # bootloader
  - efibootmgr
  - grub-efi-arm64
  - grub-efi-arm64-signed
  - shim-signed

debian_packages_noinstall_common:
  # cloud
  - cloud-init
  - cloud-utils
  - cloud-initramfs-growroot

# Architecture-specific noinstall package selection
debian_packages_noinstall: >-
  {{
    (debian_packages_noinstall_common +
     (debian_packages_noinstall_amd64 if ansible_architecture == 'x86_64' else debian_packages_noinstall_arm64))
    | unique
  }}
