---
debian_install: "{{ lookup('env', 'DEBIAN_INSTALL', default='true') | bool }}"
debian_minimal: "{{ lookup('env', 'DEBIAN_MINIMAL', default='false') | bool }}"
debian_prune: "{{ lookup('env', 'DEBIAN_PRUNE', default='false') | bool }}"
