# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "node1", primary: true do |node1|
    node1.vm.box = "bento/debian-12"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.56.10"

    node1.vm.provider "vmware_fusion" do |vmware|
      vmware.memory = 2048
      vmware.cpus = 2
      vmware.gui = false
      vmware.vmx["displayname"] = "Ansible - Debian 12 Control Plane"
    end
  end

  config.vm.define "node2", autostart: false do |node2|
    node2.vm.box = "bento/debian-12"
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.56.11"

    node2.vm.provider "vmware_fusion" do |vmware|
      vmware.memory = 2048
      vmware.cpus = 2
      vmware.gui = false
      vmware.vmx["displayname"] = "Ansible - Debian 12 Worker"
    end
  end

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
end
