---
- name: Metadata > Topology > Validate Region
  ansible.builtin.assert:
    that:
      - (metadata_topology_region | trim) | length > 0
      - (metadata_topology_region | trim) | regex_search("^[a-z]{2}-[0-9]+$") | length > 0
    success_msg: "Topology region is set"
    fail_msg: "Topology region is not set"

- name: Metadata > Topology > Set Region
  ansible.builtin.copy:
    dest: "{{ metadata_directory }}/topology-region"
    mode: "0644"
    owner: root
    group: root
    content: |
      {{ metadata_topology_region }}

- name: Metadata > Topology > Validate Zone
  ansible.builtin.assert:
    that:
      - (metadata_topology_zone | trim) | length > 0
      - (metadata_topology_zone | trim) | regex_search("^[a-z]{2}-[0-9]+[a-z]?$") | length > 0
    success_msg: "Topology zone is set"
    fail_msg: "Topology zone is not set"

- name: Metadata > Topology > Set Zone
  ansible.builtin.copy:
    dest: "{{ metadata_directory }}/topology-zone"
    mode: "0644"
    owner: root
    group: root
    content: |
      {{ metadata_topology_zone }}
