---
- name: Standard SSH
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Print Usage
      when: help | default(h) | default(false)
      failed_when: help | default(h) | default(false)
      ansible.builtin.debug:
        msg:
          - "Usage: @andreygubarev/ssh [OPTIONS]"
          - ""
          - "Options:"
          - "  -h, --help                       Show this help message and exit"
          - "  -i, --install                    Install OpenSSH server (SSH_INSTALL, default: true)"
          - "  -u, --user=andrey:andreygubarev  Add user to SSH authorized keys (SSH_USERS, default: [])"
          - "  -U, --user-key=andreygubarev     Add user to SSH authorized keys of debian user (SSH_USERS, default: [])"
          - "  -g, --group=group1               Add group to SSH authorized groups (SSH_GROUPS, default: [])"
          - "  --enable-hardening               Enable OpenSSH hardening (SSH_HARDENING, default: true)"
          - "  --enable-tcp-forwarding          Enable TCP forwarding (requires --enable-hardening)"
          - "  --enable-root-login            Enable root login (requires --enable-hardening)"

    - name: Process aliases
      ansible.builtin.set_fact:
        install: "{{ install | default(i) | default(omit) }}"
        user: "{{ user | default(u) | default(omit) }}"
        group: "{{ group | default(g) | default(omit) }}"
        user_key: "{{ user_key | default(U) | default(omit) }}"
      ignore_errors: true

    - name: Process variables
      ansible.builtin.set_fact:
        # -i or --install
        ssh_openssh: "{{ install | default(omit) }}"

        # --enable-hardening
        ssh_hardening: "{{ enable_hardening | default(omit) }}"

        # --enable-tcp-forwarding
        ssh_hardening_allow_tcp_forwarding: "{{ enable_tcp_forwarding | default(omit) }}"

        # --enable-root-login
        ssh_hardening_allow_root_login: "{{ enable_root_login | default(omit) }}"

        # -u or --user=andrey:andreygubarev (where andreygubarev is github username)
        # -U or --user-key=andreygubarev (where andreygubarev is github username)
        ssh_users: >-
          {%- if user is string and user | length > 0 -%}
          {{ [dict(["name", "key"] | zip(user | split(':'))) | combine({"state": "allow"})] }}
          {%- elif user_key is string and user_key | length > 0 -%}
          {{ [dict(["name", "key"] | zip(["debian", user_key])) | combine({"state": "allow"})] }}
          {%- else -%}
          {{ [] }}
          {%- endif -%}

        # -g or --group=group1
        ssh_groups: >-
          {%- if group is string and group | length > 0 -%}
          {{ [dict(["name"] | zip([group])) | combine({"state": "allow"})] }}
          {%- else -%}
          {{ [] }}
          {%- endif -%}
      ignore_errors: true


    - name: Include SSH role
      ansible.builtin.include_role:
        name: ssh
