---
- name: Standard Tailscale
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Print Usage
      when: help | default(h) | default(false)
      failed_when: help | default(h) | default(false)
      ansible.builtin.debug:
        msg:
          - "Usage: @adaptivegears/tailscale [OPTIONS]"
          - "Options:"
          - "  -i, --install             Install Tailscale Client (default: true)"
          - "  -t, --token               Tailscale AuthKey"
          - "  --advertise-exit-node     Advertise Exit Node"
          - "  --accept-dns              Accept DNS"
          - "  --accept-routes           Accept Routes"

    - name: Parse Arguments
      ansible.builtin.set_fact:
        install: "{{ install | default(i) | default(omit) }}"
        token: "{{ token | default(t) | default(omit) }}"
        advertise_exit_node: "{{ advertise_exit_node | default(omit) }}"
        accept_dns: "{{ accept_dns | default(omit) }}"
        accept_routes: "{{ accept_routes | default(omit) }}"
      ignore_errors: true

    - name: Prepare Variables
      ansible.builtin.set_fact:
        # -i or --install
        tailscale_install: "{{ install | default(omit) }}"
        # -t or --token
        tailscale_authkey: "{{ token | default(omit) }}"
        # --advertise-exit-node
        tailscale_advertise_exit_node: "{{ advertise_exit_node | default('') }}"
        # --accept-dns
        tailscale_accept_dns: "{{ accept_dns | default('') }}"
        # --accept-routes
        tailscale_accept_routes: "{{ accept_routes | default('') }}"
      ignore_errors: true

    - name: Include Role
      ansible.builtin.include_role:
        name: tailscale
