---
- name: Standard Tailscale
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Print Usage
      when: help | default(h) | default(false)
      failed_when: help | default(h) | default(false)
      ansible.builtin.debug:
        msg:
          - "Usage: @adaptivegears/tailscale [OPTIONS]"
          - "Options:"
          - "  -i, --install             Install Tailscale Client (TAILSCALE_INSTALL, default: true)"
          - "  -t, --token               Tailscale AuthKey (TAILSCALE_AUTHKEY)"
          - "  --login-server            Login Server (TAILSCALE_LOGINSERVER, default: '')"
          - "  --login-timeout           Login Timeout (TAILSCALE_LOGINTIMEOUT, default: 30)"
          - "  --advertise-exit-node     Advertise Exit Node (TAILSCALE_ADVERTISE_EXIT_NODE, default: '')"
          - "  --accept-dns              Accept DNS (TAILSCALE_ACCEPT_DNS, default: '')"
          - "  --accept-routes           Accept Routes (TAILSCALE_ACCEPT_ROUTES, default: '')"

    - name: Parse Arguments
      ignore_errors: true
      ansible.builtin.set_fact:
        install: "{{ install | default(i) | default(omit) }}"
        token: "{{ token | default(t) | default(omit) }}"
        login_server: "{{ login_server | default(omit) }}"
        login_timeout: "{{ login_timeout | default(omit) }}"
        advertise_exit_node: "{{ advertise_exit_node | default(omit) }}"
        accept_dns: "{{ accept_dns | default(omit) }}"
        accept_routes: "{{ accept_routes | default(omit) }}"

    - name: Prepare Variables
      ignore_errors: true
      ansible.builtin.set_fact:
        # -i or --install
        tailscale_install: "{{ install | default(lookup('env', 'TAILSCALE_INSTALL') | default('true') | bool) }}"
        # -t or --token
        tailscale_authkey: "{{ token | default(lookup('env', 'TAILSCALE_AUTHKEY')) | default(omit) }}"
        # --login-server
        tailscale_login_server: "{{ login_server | default(lookup('env', 'TAILSCALE_LOGINSERVER') | default('')) }}"
        # --login-timeout
        tailscale_login_timeout: "{{ login_timeout | default(lookup('env', 'TAILSCALE_LOGINTIMEOUT') | default(30) | int) }}"
        # --advertise-exit-node
        tailscale_advertise_exit_node: "{{ advertise_exit_node | default(lookup('env', 'TAILSCALE_ADVERTISE_EXIT_NODE') | default('')) }}"
        # --accept-dns
        tailscale_accept_dns: "{{ accept_dns | default(lookup('env', 'TAILSCALE_ACCEPT_DNS') | default('')) }}"
        # --accept-routes
        tailscale_accept_routes: "{{ accept_routes | default(lookup('env', 'TAILSCALE_ACCEPT_ROUTES') | default('')) }}"

    - name: Include Role
      ansible.builtin.include_role:
        name: tailscale
