---
- name: Standard Kubernetes
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars:
    usage: "{{ help | default(h) | default(false) }}"
  tasks:
    - name: Print Usage
      when: usage
      failed_when: usage
      ansible.builtin.debug:
        msg:
          - "Usage: @adaptivegears/standard-kubernetes [OPTIONS]"
          - "Options:"
          - "  -h, --help                       Show this help message and exit"
          - "  --topology-region                Set topology region (env: KUBERNETES_TOPOLOGY_REGION)"
          - "  --topology-zone                  Set topology zone (env: KUBERNETES_TOPOLOGY_ZONE)"
          - "  --hostname                       Set hostname (env: KUBERNETES_HOSTNAME)"
          - "  --ipv4-public                    Set public IPv4 (env: KUBERNETES_IPV4_PUBLIC)"
          - "  --ipv4-private                   Set private IPv4 (env: KUBERNETES_IPV4_PRIVATE)"

    - name: Set Facts
      ignore_errors: true
      ansible.builtin.set_fact:
        kubernetes_hostname: "{{ lookup('env', 'KUBERNETES_HOSTNAME') | default(hostname, true) | default(omit, true) }}"
        kubernetes_ipv4_public: "{{ lookup('env', 'KUBERNETES_IPV4_PUBLIC') | default(ipv4_public, true) | default(omit, true) }}"
        kubernetes_ipv4_private: "{{ lookup('env', 'KUBERNETES_IPV4_PRIVATE') | default(ipv4_private, true) | default(omit, true) }}"
        kubernetes_topology_region: "{{ lookup('env', 'KUBERNETES_TOPOLOGY_REGION') | default(topology_region, true) | default(omit, true) }}"
        kubernetes_topology_zone: "{{ lookup('env', 'KUBERNETES_TOPOLOGY_ZONE') | default(topology_zone, true) | default(omit, true) }}"

    - name: Include Role
      ansible.builtin.include_role:
        name: kubernetes
