---
- name: Standard Kubernetes
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Print Usage
      when: help | default(h) | default(false)
      failed_when: help | default(h) | default(false)
      ansible.builtin.debug:
        msg:
          - "Usage: @adaptivegears/standard-kubernetes [ROLE] [OPTIONS]"
          - "Roles:"
          - "  server                    Install k3s as a server"
          - "  agent                     Install k3s as an agent"
          - "Options:"
          - "  -i, --install             Install k3s"
          - "  -l, --labels=LABELS       Set the labels for the node"
          - "  -n, --node=NAME           Set the name of the node"
          - "  -t, --token=TOKEN         Token for joining a cluster"
          - "  --datastore=DS            Set the datastore"
          - "  --public-ip=IP            Set the external IP of the node"
          - "  --join=IP                 Join a cluster"
          - "  --pod-subnet=SUBNET       Set the pod subnet"
          - "  --service-subnet=SUBNET   Set the service subnet"
          - "  --enable-embeddedregistry Enable embedded registry (default: true)"
          - "  --enable-localstorage     Enable local storage (default: false)"
          - "  --enable-istio            Enable Istio (env: KUBERNETES_ENABLE_ISTIO, default: false)"
          - "  --tailscale=TOKEN         Enable Tailscale Integration (env: TAILSCALE_AUTHKEY)"
          - "  --tailscale-advertise-exit-node     Enable Tailscale Exit Node (env: TAILSCALE_ADVERTISE_EXIT_NODE)"
          - "Examples:"
          - "  $ getansible.sh -- @adaptivegears/standard-kubernetes server -t secret"
          - "  $ getansible.sh -- @adaptivegears/standard-kubernetes agent -t secret -j 127.0.0.1"

    - name: Assert Arguments
      ansible.builtin.assert:
        that:
          - COMMAND is defined
          - COMMAND in ['server', 'agent']
        msg: "Role is required and must be either 'server' or 'agent'"

    - name: Parse Arguments
      ansible.builtin.set_fact:
        role: "{{ COMMAND }}"
        install: "{{ install | default(i) | default(true) }}"
        token: "{{ token | default(t) | default(omit) }}"
        datastore: "{{ datastore | default(omit) }}"
        join: "{{ join | default(j) | default(omit) }}"
        public_ip: "{{ public_ip | default(omit) }}"
        node: "{{ node | default(n) | default('') }}"
        labels: "{{ labels | default(l) | default([]) }}"
        enable_embeddedregistry: "{{ enable_embeddedregistry | default(true) }}"
        enable_localstorage: "{{ enable_localstorage | default(false) }}"
        enable_istio: "{{ enable_istio | default(omit) }}"
        tailscale: "{{ tailscale | default(omit) }}"
        tailscale_advertise_exit_node: "{{ tailscale_advertise_exit_node | default(omit) }}"
        pod_subnet: "{{ pod_subnet | default(omit) }}"
        service_subnet: "{{ service_subnet | default(omit) }}"

    - name: Prepare Variables
      ansible.builtin.set_fact:
        kubernetes_role: "{{ role }}"
        # -n or --node
        kubernetes_node: "{{ node | default(omit) }}"
        # -l or --labels
        kubernetes_labels: "{{ labels | default([]) }}"
        # -i or --install
        kubernetes_install: "{{ install | default(false) }}"
        # --token=secret
        kubernetes_token: "{{ token | default(omit) }}"
        # --join=127.0.0.1 (default: 127.0.0.1)
        kubernetes_apiserver: "{{ join | default(omit) }}"
        # --datastore=sqlite3:///var/lib/rancher/k3s/server/db/sqlite.db
        kubernetes_datastore: "{{ datastore | default(omit) }}"
        # --public-ip=1.1.1.1
        kubernetes_public_ip: "{{ public_ip | default(omit) }}"
        # --enable-embeddedregistry
        kubernetes_enable_embeddedregistry: "{{ enable_embeddedregistry | default(true) }}"
        # --enable-localstorage
        kubernetes_enable_localstorage: "{{ enable_localstorage | default(false) }}"
        # --enable-istio
        kubernetes_enable_istio: "{{ enable_istio | default(omit) }}"
        # --enable-tailscale
        kubernetes_tailscale_authkey: "{{ tailscale | default(omit) }}"
        # --tailscale-advertise-exit-node
        kubernetes_tailscale_advertise_exit_node: "{{ tailscale_advertise_exit_node | default(omit) }}"
        # --pod-subnet
        kubernetes_pod_subnet: "{{ pod_subnet | default(omit) }}"
        # --service-subnet
        kubernetes_service_subnet: "{{ service_subnet | default(omit) }}"

    - name: Include Role
      ansible.builtin.include_role:
        name: kubernetes
