---
- name: Standard Kubernetes
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars:
    usage: "{{ help | default(h) | default(false) }}"
  tasks:
    - name: Print Usage
      when: usage
      failed_when: usage
      ansible.builtin.debug:
        msg:
          - "Usage: @adaptivegears/standard-kubernetes"
