---
- name: Standard Tailscale
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Print Usage
      when: help | default(h) | default(false)
      failed_when: help | default(h) | default(false)
      ansible.builtin.debug:
        msg:
          - "Usage: @adaptivegears/tailscale [OPTIONS]"
          - "Options:"
          - "  -i, --install             Install Tailscale Client (TAILSCALE_INSTALL, default: true)"
          - "  -t, --token               Tailscale AuthKey (TAILSCALE_AUTHKEY)"
          - "  --login-server            Login Server (TAILSCALE_LOGINSERVER, default: '')"
          - "  --login-timeout           Login Timeout (TAILSCALE_LOGINTIMEOUT, default: 30)"
          - "  --advertise-exit-node     Advertise Exit Node (TAILSCALE_ADVERTISE_EXIT_NODE, default: '')"
          - "  --accept-dns              Accept DNS (TAILSCALE_ACCEPT_DNS, default: '')"
          - "  --accept-routes           Accept Routes (TAILSCALE_ACCEPT_ROUTES, default: '')"

    - name: Set Facts
      ignore_errors: true
      ansible.builtin.set_fact:
        tailscale_install: "{{ lookup('env', 'TAILSCALE_INSTALL') | default(install, true) | default(i, true) | default('true', true) | bool }}"
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_AUTHKEY') | default(token, true) | default(t, true) | default(omit, true) }}"
        tailscale_login_server: "{{ lookup('env', 'TAILSCALE_LOGINSERVER') | default(login_server, true) | default('', true) }}"
        tailscale_login_timeout: "{{ lookup('env', 'TAILSCALE_LOGINTIMEOUT') | default(login_timeout, true) | default(30, true) | int }}"
        tailscale_advertise_exit_node: "{{ lookup('env', 'TAILSCALE_ADVERTISE_EXIT_NODE') | default(advertise_exit_node, true) | default('', true) }}"
        tailscale_accept_dns: "{{ lookup('env', 'TAILSCALE_ACCEPT_DNS') | default(accept_dns, true) | default('', true) }}"
        tailscale_accept_routes: "{{ lookup('env', 'TAILSCALE_ACCEPT_ROUTES') | default(accept_routes, true) | default('', true) }}"

    - name: Include Role
      ansible.builtin.include_role:
        name: tailscale
