---
debian_install: "{{ lookup('env', 'DEBIAN_INSTALL', default='true') | bool }}"
debian_minimal: "{{ lookup('env', 'DEBIAN_MINIMAL', default='false') | bool }}"
debian_prune: "{{ lookup('env', 'DEBIAN_PRUNE', default='false') | bool }}"
debian_hostname: "{{ (lookup('env', 'DEBIAN_HOSTNAME') or lookup('ansible.builtin.file', '/var/lib/instance-metadata/hostname', errors='ignore')) }}"

debian_topology_region: |
  {{
    (
      (lookup('env', 'DEBIAN_TOPOLOGY_REGION') | trim) or
      (lookup('ansible.builtin.file', '/var/lib/instance-metadata/topology-region') | trim)
    ) | mandatory
  }}
