---
- name: Restart systemd-timesyncd
  ansible.builtin.systemd_service:
    name: systemd-timesyncd
    state: restarted

- name: Debian > System | Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted

- name: Debian > DNS | Restart
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted
